### ISSUE TITLE
json11 won't autobuild when you run ./build.sh

### ISSUE THREAD

**Issue by inflex** [inflex/OpenBoardView#1]
For what ever reason, something I have yet to work out, the json11 src folder never seems to download or build on its own.

```
CMake Error at src/CMakeLists.txt:27 (add_library):
  Cannot find source file:

    json11/json11.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: json11
CMake Error: Cannot determine link language for target "json11".

```

**Comment by alx741** [comment]
How are you compiling the project?

**Comment by inflex** [comment]
I just run the ./build.sh ,  everything goes nicely except for the json11 build, which I have to manually set up using the Dropbox/json11 copy.   

Not that it's hindering *me* specifically but it's something of a stumbling block for those who want to build it themselves without the issues.

I noticed that the ./src/json11 is a link/reference unlike the other folders in ./src

**Comment by alx741** [comment]
Maybe I'm just dumb... but I can't find the `build.sh` script anywhere in the code base, nor the `src` directory. I notice a *Visual Studio* file there, maybe it's supposed to be a *VS* project (?)

**Comment by inflex** [comment]
Ah, no, you have to pull the specific branch.... that's caught me off so many times too.  Let me give you the sequence :)

`git clone -b inflex-ui-features https://github.com/inflex/OpenBoardView.git`

**Comment by inflex** [comment]
The json11 problem has been solved;

Need to run this in the OpenBoardView folder after cloning:

    git submodule update --init --recursive

**Comment by alx741** [comment]
Awesome!
