### ISSUE TITLE
HI! could anyone make an executable for windows or os

### ISSUE THREAD

**Issue by kikef333** [inflex/OpenBoardView#26]
could anyone make an executable for windows or os for those of us who don't know anything about decoding?

PLEASEEEE!!!!!

Best Regards!!!

**Comment by inflex** [comment]
@kikef333 what platform do you have? I can build you a self-contained binary of the inflex-ui-features branch.

**Comment by inflex** [comment]
@kikef333 attached.  Just unpack this somewhere.  When you run it it'll create its own .conf and .history files in that folder.  Requires no installation/setup.

Only thing you might want to immediately change is the default window X/Y size in the obv.conf file to what ever value you prefer.


[openflexboardview.zip](https://github.com/inflex/OpenBoardView/files/392297/openflexboardview.zip)

**Comment by inflex** [comment]
Here's the latest binary build from today so far - it includes a significant feature add, namely annotations, and also has adjustable dpi for if you're using 2K~4K screens and want to appropriately scale up.

[openflexboardview-with-annotations-dpi.zip](https://github.com/inflex/OpenBoardView/files/393822/openflexboardview-with-annotations-dpi.zip)

**Comment by inflex** [comment]
Release 3 has just been put up @kikef333 

https://github.com/inflex/OpenBoardView/releases/tag/R3
