### ISSUE TITLE
Compiling under Windows 10 wsl2 ubuntu-18.04  CR/LF issue with solution

### ISSUE THREAD

**Issue by stray77** [inflex/OpenBoardView#3]
stray@3770K:/mnt/d/github/openboardview$ ./build.sh
-bash: ./build.sh: /bin/sh^M: bad interpreter: No such file or directory
stray@3770K:/mnt/d/github/openboardview$ sed -i -e 's/\r$//' build.sh
stray@3770K:/mnt/d/github/openboardview$ ./build.sh
Compiling OpenBoardView using 8 threads (release build)...

**Comment by inflex** [comment]
Blimey, will have to test this out.  Since the creation of the mingw64 cross build I've not used it under windows at all. Interesting that it doesn't like the \r, since that likely was in there for the sake of Windows originally.
