### ISSUE TITLE
Latest Binaries

### ISSUE THREAD

**Issue by inflex** [inflex/OpenBoardView#36]
While everything is a bit haphazard I'll upload binaries here and update this post each time.

EDIT: We're now at the stage where OBV/OFBV are starting to stabilize nicely, so now the "preferred binaries" are located at http://openboardview.org

**Comment by inflex** [comment]
Colours now adjustable from within.  Still don't have a colour picker, so for now entry is a quad-byte RGBA hex entry.

![ss](https://cloud.githubusercontent.com/assets/5660591/17560950/4f85a748-5f67-11e6-9c71-3246433043af.png)

**Comment by piernov** [comment]
OS X & Win32 builds available here: https://github.com/piernov/OpenBoardView/releases
Built automatically using Travis. Work on the Win32 build is still ongoing (that's why it's on the wip/mingw-cross branch) but it should be more or less working.
I did not try the OS X build but there is no reason for it not to work.

**Comment by inflex** [comment]
Thanks for that @piernov .  Is that using the new crosscompile build system you worked on?

**Comment by inflex** [comment]
Zoom-pan on search results added
Removed DDS fluff (thanks @piernov )
Fixed up memory leaks
Fixed up some crashes / invalid file handling

**Comment by piernov** [comment]
Second build: https://github.com/piernov/OpenBoardView/releases/tag/N2
Based on inflex-ui-features at 961ddde623ba49f2e660d07aeac385d4c4203e0d, with #39 merged.
Again, built automatically by Travis, and OS X build not tested.

To complete inflex-ui-features's Changelog:
 - Added OpenGL 1.1 renderer (set as default for now). Tested on Riva TNT2 (don't expect great performances though).

**Comment by piernov** [comment]
Also updated the Android build: http://servers.piernov.org/~piernov/BoardView/OpenBoardView-N2.apk

**Comment by inflex** [comment]
There was a report of a small selection of virus scanners getting a false positive on the earlier binaries. I've changed the VS2015 compile optimisations and it's now reporting back "fully clean".

**Comment by piernov** [comment]
Third build: https://github.com/piernov/OpenBoardView/releases/tag/N3
Nothing really exciting this time.

**Comment by inflex** [comment]
I'm somewhat glad we're getting to that point :+1:  :)

**Comment by piernov** [comment]
Fourth build: https://github.com/piernov/OpenBoardView/releases/tag/N4

- Use system fonts (Liberation Sans, DejaVu Sans or Arial) instead of `asset/*.ttf`

**Comment by piernov** [comment]
Fifth build: https://github.com/piernov/OpenBoardView/releases/tag/N5

From `inflex/inflex-ui-features`
- Fix arrow keys and file extension case sensitivity on Linux
- Limit .fz pin radius to 0.5 minimum
- Theme adjustements

From `piernov/wip/file-path`
- Various changes to the config/history file path handling
- Also fixes config/history file path on Win32 OpenGL build

From `piernov/wip/cpack-deb`
 - Build Debian package automatically on Travis with CPack. (tested only on Ubuntu 16.04, thanks @sticmac)

**Comment by inflex** [comment]
Latest win build now adds;
* selectable primary flip mode (viewport or mouse pointer)
* Same-net web, connects each other pin on the same net with a line from the current pin (will probably add a nicer branching algorithm in the future to reduce the level of fan-out).  Current NC, Unknown and GND nets are not drawn with this (meaningless or too prolific).

20160817-00H44 4addfe22aa8fd6800bf1ab8a2bf139388a1cd611

**Comment by piernov** [comment]
Sixth build: https://github.com/piernov/OpenBoardView/releases/tag/N6

From `inflex/inflex-ui-features`
- See @inflex comment above

From `piernov/wip/file-path`
- Same as before
- History file is now stored in `%LOCALAPPDATA%/OpenBoardView` on Windows and `$HOME/.local/share/openboardview` on Linux

From `piernov/wip/cpack-deb`
 - Same as before

**Comment by piernov** [comment]
Seventh build: https://github.com/piernov/OpenBoardView/releases/tag/N7
From `inflex/inflex-ui-features`
- Build revision now displayed in Help→About and with `openboardview -V`

From `piernov/fix/win-font-loading`
- Fix font loading on Windows. Win32 build was broken since N4. Thanks @mrxordi.

PS: OS X build currently unavailable, Travis seems to have some issue with their OS X environment. May come back later.

**Comment by piernov** [comment]
Eighth build: https://github.com/piernov/OpenBoardView/releases/tag/N8
From `inflex/inflex-ui-features`
- Finally fix font loading on Windows.
- Merge the config/history file path changes

From `piernov/android-support`
- Rebased on inflex/inflex-ui-features
- Font was changed to system's DroidSans.ttf with size 30.
- Config/history files now work and are stored in the application data folder (either external or internal).

PS: OS X build still lagging behind, may be available later.

**Comment by piernov** [comment]
Tenth build: https://github.com/piernov/OpenBoardView/releases/tag/N10
From `inflex/inflex-ui-features`
- Various cleanups (delete XCode project, remove json11, remove some warnings, etc…)
- Fix build with Visual Studio (Dx9) and add support for generating Visual Studio solution using CMake (OpenGL).

From `piernov/feat/asc-support`
- Add support for `*.asc`. See #43, #55 and OpenBoardView/OpenBoardView#45.
