### ISSUE TITLE
Configurable renderer

### ISSUE THREAD

**Issue by piernov** [inflex/OpenBoardView#38]
In previous commits I added support for GLES 2 and GL 1 renderers. Since af36cbdabf1fd5fe53c0d087e6d7e8e5c8663cc9 the default renderer is now GL 1 but it may not be what we want.

In all cases, we want to be able to choose which renderer to use at runtime. It would be nice if a configuration option is added for this. For now the global variable `renderer` in `main_opengl.cpp` sets it, choosing from the `Renderer` enum. (added in a27dd33b2b5083f6cff475c8b8b5ba53b1befb5c)

**Comment by inflex** [comment]
Is this something we can change at runtime?  Setting a parameter shouldn't be an issue; something as simple as "renderer = ",  perhaps give me a few name options to  select, or we can just make it a numerical one (to prevent typos) and use # comments in the config to describe the options, like

# 1 - GLES2
# 2 - GL1
# 3 - DX9

**Comment by inflex** [comment]
commit: 096c74fdcd63617462e075e5647989c11dd484c0

Added -r [1..3] option, also just 'renderer = [1..3]' in the conf file, mapped to;

```
			case 1: g.renderer = OPENGL1; break;
			case 2: g.renderer = OPENGL3; break;
			case 3: g.renderer = OPENGLES2; break;

```
