### ISSUE TITLE
More flexible path for history and config file

### ISSUE THREAD

**Issue by piernov** [inflex/OpenBoardView#40]
Currently the path are hard-coded for each supported platforms: https://github.com/inflex/OpenBoardView/blob/inflex-ui-features/src/openboardview/main_opengl.cpp#L206
(quick fix I did when working on OS X support).
Since I added support for the OpenGL renderer on Windows using `main_opengl.cpp` (see #39), we would have to add 3 other `#ifdef` to use the correct paths on Windows. That's not a real solution and we need to have a configurable prefix.

**Comment by inflex** [comment]
What ideas do you have for a more configurable option?  CLI parameter passed for a "config path" ?

**Comment by piernov** [comment]
That's ok. 3 different default prefixes according to the target system and the user could choose a custom one from the command line.
