### ISSUE TITLE
Motherboard outline wrong shape

### ISSUE THREAD

**Issue by tommis** [inflex/OpenBoardView#42]
Thinkpad X220 motherboard is displayed like so as a square when in real life outline is nothing like it.

![2016-08-14-010156_3600x1080_scrot](https://cloud.githubusercontent.com/assets/279171/17645896/2c19f812-61bb-11e6-815a-59eab7f08d84.png)

Heres the file. I added txt extension to the bdv file so it would upload.
[x220.boardview.H0225-1.bdv.txt](https://github.com/inflex/OpenBoardView/files/416785/x220.boardview.H0225-1.bdv.txt)

**Comment by piernov** [comment]
Nothing we can do there, the decoded file says:
```
<<format.asc>>
      3.020      5.868      0.000
      3.020     -5.868      0.000
     -3.020     -5.868      0.000
     -3.020      5.868      0.000
      3.020      5.868      0.000
```
so that's how the engineer has drawn it.

**Comment by inflex** [comment]
That's caught me out a few times as well.  Sadly, yes, nothing can be done because the engineers didn't supply the data as @piernov indicates.
