### ISSUE TITLE
Problem when installing on mac

### ISSUE THREAD

**Issue by traajkumar** [inflex/OpenBoardView#61]
Process:         launchd [181]
Path:            /Volumes/OpenBoardView/openboardview.app/Contents/MacOS/openboardview
Identifier:      launchd
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [90]

Date/Time:       2016-11-01 20:00:07.434 +0530
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Interval Since Last Report:          1160130 sec
Crashes Since Last Report:           332
Per-App Crashes Since Last Report:   14
Anonymous UUID:                      21D12F48-DB99-4F72-AB5A-643557E93409

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0xfffffffffffffff8
Crashed Thread:  Unknown

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0xfffffffffffffff8

Binary images description not available

Model: MacBookPro5,1, BootROM MBP51.007E.B06, 2 processors, Intel Core 2 Duo, 2.8 GHz, 8 GB, SMC 1.33f8
Graphics: NVIDIA GeForce 9400M, NVIDIA GeForce 9400M, PCI, 256 MB
Memory Module: global_name
Bluetooth: Version 2.4.5f3, 2 service, 19 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: MATSHITADVD-R   UJ-868
USB Device: Built-in iSight, 0x05ac  (Apple Inc.), 0x8507, 0x24400000 / 2
USB Device: StoreJet Transcend, 0x174c  (ASMedia Technology Inc.), 0x5106, 0x26200000 / 2
USB Device: BRCM2046 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0x06100000 / 2
USB Device: Bluetooth USB Host Controller, 0x05ac  (Apple Inc.), 0x8213, 0x06110000 / 3
USB Device: Apple Internal Keyboard / Trackpad, 0x05ac  (Apple Inc.), 0x0236, 0x04600000 / 3
USB Device: IR Receiver, 0x05ac  (Apple Inc.), 0x8242, 0x04500000 / 2

**Comment by inflex** [comment]
I'm fairly sure OBV requires 10.7.2 or later; Snow Leopard is not supported.  Trying to now dig back where this was defined.

**Comment by piernov** [comment]
It requires 10.9, but it can be built on 10.7 with a simple fix: https://github.com/piernov/OpenBoardView/commit/be6123c5d3a9f72bf700f39a4e5ce9493bc1bd2a
(I couldn't get Travis to build for 10.7 successfully though, but it worked on my iMac 5,2.)

However I don't think it will build on 10.6. Since you have a MacBookPro5,1 which has OS X support up to 10.11, you should probably upgrade OS X to a newer version.

**Comment by traajkumar** [comment]
But my macbookpro not supporting for the new versions of MAC OS. Because my mac book pro is Core 2 Duo. Is there any solution to use this software or any compatible packages available ?

**Comment by inflex** [comment]
Thanks for the clarification @piernov .  I'll update the website and other pages referring to it.
