### ISSUE TITLE
the App can't open bardviews via commnad line

### ISSUE THREAD

**Issue by dn-kolesnikov** [inflex/OpenBoardView#62]
the App can't open bardviews via commnad line
I need set file association for DE, but OpenBoardView can't get command line parameters

**Comment by inflex** [comment]
Can you cut-paste an example of your attempt to run / load from the command line?

OBV should now be using the -i <boardfile> parameter but I think it still does fall back to loading if the file is the only parameter.

**Comment by dn-kolesnikov** [comment]
Yes, i ran without any parameters, i tried run with -i parameter and the
boardview opened!

Sory for my stupid :)

**Comment by piernov** [comment]
You should be using OpenBoardView/OpenBoardView nowadays, not @inflex ' fork.
The feature @inflex is referring to was added as of OpenBoardView/OpenBoardView@0cc08bd361abeceaf3c9a00bdd59e52ca13557c4 and no release was made since then. You can still grab the latest code from the master branch.
