### ISSUE TITLE
Which version would work with OS X 10.8.5?

### ISSUE THREAD

**Issue by marinnen128** [inflex/OpenBoardView#63]
Is there a .dmg file I could download that would work with OS X 10.8.5?

**Comment by piernov** [comment]
You should consider using a more recent version of OS X as old versions won't receive security fixes anymore. Most popular software require 10.9 nowadays too.
There are some workaround here to have OpenBoardView build back to 10.7: https://github.com/piernov/OpenBoardView/tree/fix/osx-10.7
There's no DMG, you'll need to build it manually.

**Comment by marinnen128** [comment]
I am a total newbie here. Please let me know where can I learn how to build the DMG manually as you susggest. As a side, would any of the old releases (7.2, 7.1, 7, 6, ...) work on OS X 10.8.5?
Thanks.

**Comment by marinnen128** [comment]
Point of clarification: what I meant is - would any of the old releases' (7.2, 7.1, 7, 6, ...) DMGs work on OS X 10.8.5? Clearly that would be more reliable and quicker way to start using the OpenBoardView, which is my primary objective.
