### ISSUE TITLE
Errors with running openboardview.sh

### ISSUE THREAD

**Issue by larienciel** [inflex/OpenBoardView#7]
Hi there, 

I am trying to run openboardview on Docker Ubuntu. I managed to build and all but when it comes to running ./openboardview.sh, it shows Error: Failed to connect to the Mir Server. 

It would be much appreciated if you could kindly advise if there is a way to go about it. Please find the below snapshot of the error message for your reference. 

Thanks. 
<img width="573" alt="Screenshot 2020-04-21 at 00 31 48" src="https://user-images.githubusercontent.com/63986037/79775929-8ab1ce00-8367-11ea-93e9-e33ddbc22358.png">

**Comment by inflex** [comment]
I have no idea about that, haven't ever tried with docker, and certainly am not sure what the "Mir Server" is ?

Try just run ./bin/openboardview

**Comment by piernov** [comment]
Mir is an alternative to Xorg. I have no idea why it's trying to using it, but in any case running inside Docker won't work. There's no Xorg server running to show the GUI. It's the same problem as running any GUI app inside Docker, not specific to OpenBoardView.

Anyway if you are on macOS just run the macOS build.

**Comment by larienciel** [comment]
Hi there, thank you so much for all your invaluable feedback and input.
