### ISSUE TITLE
OpenBoardView-R10.1 not opening on Mac

### ISSUE THREAD

**Issue by hasloku** [inflex/OpenBoardView#8]
OpenBoardView-R10.1 with openboard data support will get installed on Mac without any issue.
But App is not opening. I am using High Sierra 10.13.6
Any solution??

**Comment by inflex** [comment]
Will be catching up to the master branch soon and reapplying this.  The OBD project is going to get shuffled around again so for now at least this is a bit of a dead end.

**Comment by hasloku** [comment]
Thanks
